name: Playlist Guncelle

on:
  schedule:
    - cron: '0 */6 * * *' # 6 saatte bir otomatik çalışır
  workflow_dispatch: # Senin manuel başlatman için buton ekler

jobs:
  build:
    runs-on: ubuntu-latest # İşletim sistemi
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: setup-python@v4
        with:
          python-version: '3.9'

      - name: Tarayici ve Playwright Kur
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Kanallari Tara (Playwright ile)
        run: python kanallar.py

      - name: Playlisti Kaydet
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Playlist Playwright ile guncellendi" || exit 0
          git push
          
