name: Ortaligi Topla

on: workflow_dispatch

permissions:
  contents: write

jobs:
  temizlik:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Cek
        uses: actions/checkout@v4

      - name: Klasor Olustur ve Tasi
        run: |
          mkdir -p logolar
          mv *.jpg logolar/ 2>/dev/null || true
          
      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name "Temizlik Robotu"
          git config --global user.email "robot@github.com"
          git add .
          git commit -m "Resimler logolar klasorune tasindi"
          git push
          
